import Head from 'next/head'

import { Hero } from '@/sections/Hero/Hero'

const HeroData = {
  title: "Managed agency selection",
  subtitle: "Strengthen your onboarding process"
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero {...HeroData} />
      </div>
    </>
  )
}
